#!/usr/bin/env bash
#

apt-get update

apt-get install -y nginx

echo "Hello World!" > ~/etc/nginx/html/hello.html

echo "server {
    listen 80;
    listen [::]80 default_server;
    root ~/etc/nginx/html;
    index hello.html
    }
}" > /etc/nginx/sites-available/default

service nginx restart
