#!/usr/bin/env bash
# Runs a nginx in the server

sudo apt-get update
sudo apt-get install nginx
sudo service nginx start

ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo service nginx restart
