#!/usr/bin/env bash
#

apt-get update

apt-get install -y nginx

echo "server {
    listen 80;
    server_name ubuntu@100.26.159.135;

    location / {
        return 200 'Hello World!';
    }
}" > /etc/nginx/sites-available/default
