#!/usr/bin/env bash
# Runs a nginx in the server

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start

sudo mkdir -p /etc/nginx/html

echo "Hello World!" | sudo tee /etc/nginx/html/index.html

printf %s "server{
listen 80;
listen [::]:80;
root /etc/nginx/html;
index index.html;
}" | sudo tee /etc/nginx/sites-available/default

printf %s "server{
listen 80 default_server;
listen [::]:80 default_server;
root /etc/www/html;
index index.html;
location /redirect_me {
  return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
  }
}" | sudo tee /etc/nginx/sites-available/redirect

sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

sudo nginx -t
sudo service nginx restart
