#!/usr/bin/env bash
# Runs a nginx in the server

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start

sudo mkdir -p /etc/nginx/html

echo "Hello World!" | sudo tee /etc/nginx/html/index.html
echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404.html

printf %s "server{
listen 80 default_server;
listen [::]:80 default_server;
add_header X-Served-By $HOSTNAME;
root /etc/nginx/html;
index index.html;

error_page 404 /404.html;
location /404 {
  root /etc/nginx/html;
  internal;
  }

location /redirect_me {
  return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
  }

}" | sudo tee /etc/nginx/sites-available/default

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo nginx -t

sudo service nginx restart
