#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get install -y haproxy

echo 's/ENABLED=0/ENABLED=1/' | sudo tee -a /etc/default/haproxy

sudo nano /etc/haproxy/haproxy.cfg

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg

frontend programming101.tech
    timeout client  30000
    bind 0:80
    default_backend programming101.tech_backend

backend programming101.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 512357-web-01 100.26.159.135:80 check
    server 512357-web-02 54.157.147.219:80 check
EOT

sudo service haproxy restart
