#!/usr/bin/env bash
# displays a line and if an SIGTERM send sends another line

pid_file="/var/run/myscript.pid"
echo $$ > "$pid_file"

intsig() {
        echo "Y U no love me?!"
}

termsig() {
        echo "I hate the kill command"
	rm -f "$pid_file"
	exit 0
}

quitsig() {
	rm -f "$pid_file"
	exit 0
}

trap termsig SIGTERM
trap intsig SIGINT
trap quitsig SIGQUIT

while true; do
        echo "To infinity and beyond"
        sleep 2
done
