#!/usr/bin/env bash
# Print "Best School" 10 times but 9th print is "Hi" using a while loop
counter=0


while [ $counter -lt 11 ]; do
	if [ $counter -eq 9 ]
	then
	    echo "Hi"
	else   
            echo "Best School"
	fi
        ((counter++))
done
