#!/usr/bin/env bash
# Print "Best School" 10 times but 4th and 8th print using a while loop
counter=0


while [ $counter -lt 10 ]; do
        if [ $counter -eq 3 ]
        then
            echo "bad luck"
	elif [ $counter -eq 7 ]
	then
	    echo "good luck"
        else
            echo "Best School"
        fi
        ((counter++))
done
