#!/usr/bin/env bash
# prints numbers from 0-20 but if number is (4,9,18) print different
counter=1


while [ $counter -lt 21 ]; do
        case $counter in
    	"3")
        	echo "bad luck from China"
        	;;
    	"8")
        	echo "bad luck from Japan"
        	;;
    	"16")
        	echo "bad luck from Italy"
        	;;
    	*)
        	echo "$counter"
        	;;
	esac
        ((counter++))
done
