#!/usr/bin/env bash
# prints numbers from 0-20 but if number is (4,9,18) print different
counter=0


while [ $counter -lt 20 ]; do
	((counter++))
	echo "$counter"
        case $counter in
    	"4")
        	echo "bad luck from China"
        	;;
    	"9")
        	echo "bad luck from Japan"
        	;;
    	"17")
        	echo "bad luck from Italy"
        	;;
    	*)
        	;;
	esac
done
