#!/usr/bin/env bash
# write a clock that goes from 0:00 to 12:59
hour=0


while [ $hour -lt 13 ]; do
        echo "Hour: $hour"

	minute=0


	while [ $minute -lt 60 ]; do
		echo "$minute"
		((minute++))
	done


	((hour++))
done
