#!/usr/bin/env bash
# Prints information about a file school
file="school"


if [ -e "$file" ]; then
	echo "school file exists" #file exists

	if [ -s "$file" ]; then
		echo "school file is not empty"  #file isnt empty
	else
		echo "school file is empty" #file is empty
	fi


	if [ -f "$file" ]; then
		echo "school is a regular file"  #file is regular
	fi
else
	echo "school file does not exist"  #file doesnt exist
fi
