#!/usr/bin/env bash
# cofigurates localhost to 127.0.0.2 and facebook.com to 8.8.8.8

local_mapping="127.0.0.2	localhost"
facebook_mapping="8.8.8.8	facebook.com"

echo -e "$local_mapping\n$facebook_mapping" > /etc/hosts
